config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :students do
    post :approve_student, on: :member
  end
  resources :institutions
  root to: "home#index"
  get :register, to: 'students#register'
  post :register_student, to: 'students#register_student'
  get :pending_students, to: 'students#pending_students'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :institution
  default_scope { where(pending: false) }
  scope :pending_students, -> { unscope(where: :pending).where(pending: true) }
  scope :search_by_full_name, -> (full_name) { where("full_name LIKE ?", "%#{full_name}%") }
  scope :search_by_name, -> (name) { where('institutions.name LIKE ?', "%#{name}%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: %i[ show edit update destroy ]

  # GET /institutions or /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1 or /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions or /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: "Institution was successfully created." }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1 or /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: "Institution was successfully updated." }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1 or /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: "Institution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def institution_params
      params.require(:institution).permit(:name, :address, :phone)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  helper_method :sort_column, :sort_direction
  skip_before_action :authenticate_user!, only: [:register, :register_student]
  before_action :set_student, only: %i[ show edit update destroy approve_student]

  # GET /students or /students.json
  def index
    @students = Student.joins(:institution)
    if params[:full_name].present? && params[:name].present?
      @students = @students.where('students.full_name LIKE ? AND institutions.name LIKE ?', "%#{params[:full_name]}%","%#{params[:name]}%")
    elsif params[:full_name].present?
      @students = Student.search_by_full_name(params[:full_name])
    elsif params[:name].present?
      @students = @students.search_by_name(params[:name])
    end
    @students = @students.order(sort_column + " " + sort_direction)
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def register
    @student = Student.new
  end

  def register_student
    @student = Student.new(student_params)
    @student.pending = true
    if @student.save
      redirect_to register_path
      # format.html { redirect_to @student, notice: "Student was successfully registered." }
      # format.json { render :register, status: :ok, location: @student }
    else
        format.html { render :register, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
  end

  def pending_students
    @pending_students = Student.pending_students
  end

  def approve_student
    if @student.update_attributes(pending: false)
      redirect_to pending_students_path
    end
  end

  private

  def sort_column
    ['students.full_name', 'institutions.name'].include?(params[:sort]) ? params[:sort] : "students.full_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.unscoped.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:full_name, :address, :email, :mobile, :institution_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Student Manage App</h1>
<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></br>
  <%= link_to 'Students', students_path %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %></br>
  <%= link_to 'Sing up', new_user_registration_path %> </br>
<% end %>
<br>
<%= link_to 'Register Student', register_path %>

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
        <% institution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.address %></td>
        <td><%= institution.phone %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institution.phone %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentDbNidhi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Singed as
      <%= current_user.email %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student, local: true) do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :institution_id %>
    <%= form.select :institution_id, options_from_collection_for_select(Institution.all, :id, :name), {}, class: "form-control form-control-lg" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Home', root_path %>
<h1>Students</h1>
<div class="col-md-12">
<%= form_tag students_path, :method => 'get' do %>
  <p>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <%= text_field_tag :full_name, params[:full_name] %>
    <%= text_field_tag :name, params[:name] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= sortable "students.full_name", "Name" %></th>
      <th>Address</th>
      <th>Email</th>
      <th><%= sortable "institutions.name", "institution"%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.full_name %></td>
        <td><%= student.address %></td>
        <td><%= student.email %></td>
        <td><%= student.institution.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Student', new_student_path %>
<br>
<%= link_to 'Pending Students List', pending_students_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form'%>

<%= link_to 'Back', students_path %>

app/views/students/pending_students.html.erb
<p id="notice"><%= notice %></p>

<h1>Pending Students</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Institution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pending_students.each do |student| %>
      <tr>
        <td><%= student.full_name %></td>
        <td><%= student.address %></td>
        <td><%= student.email %></td>
        <td><%= student.institution.name %></td>
        <td><%= link_to 'Approve', approve_student_student_path(student), method: :post %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back to Student List', students_path %>

app/views/students/register.html.erb
<h1>New Student</h1>

<%= form_with(model: @student, url: register_student_path(@student), method: "post") do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="form-group">
    <%= form.label :institution_id %>
    <%= form.select :institution_id, options_from_collection_for_select(Institution.all, :id, :name), {}, class: "form-control form-control-lg" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>  

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @student.institution_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>